@include('elements.dashboard.pictures_kpi.answered')
@include('elements.dashboard.pictures_kpi.answered_time')
@include('elements.dashboard.pictures_kpi.abandoned')
@include('elements.dashboard.pictures_kpi.abandoned_time')
@include('elements.dashboard.pictures_kpi.sla_day')
